import type { NextPage } from 'next';
import Head from 'next/head';
import { useContext, useEffect, useRef } from 'react';
import Pusher from 'pusher-js';
import styles from '../styles/Home.module.css';
import { DiceContext } from '../context/DiceContext';
import Dices from '../components/Dices/Dices';

const Home: NextPage = () => {
  const {
    userName,
    setUserName,
    diceNumber,
    diceHistory,
    setDiceHistory,
    selectedDice
  } = useContext(DiceContext);

  const initialRender = useRef(true);

  useEffect(() => {
    const pusher = new Pusher('f31e8d4fbd3ca3339a4d', {
      cluster: 'eu'
    });

    const channel = pusher.subscribe('my-dice');
    channel.bind('my-event', function (data: string) {
      alert(JSON.stringify(data));
    });
  }, [])


  useEffect(() => {
    if (initialRender.current) {
      initialRender.current = false;
    } else {
      console.log("Diced");
      setDiceHistory([...diceHistory, `${userName} a lancé un dés ${selectedDice} et a obtenu -> ${diceNumber} ! `])
    }
  }, [diceNumber])

  return (
    <div className={styles.container}>
      <Head>
        <title>Dice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dice.png" />
      </Head>

      <main className={styles.main}>
        Historique: {diceHistory}
        <input value={userName} onChange={e => setUserName(e.target.value)} />
        <Dices />
      </main>
    </div >
  )
}

export default Home;
